Repository kata-containers/packaging, pull requests merged in 2020-10, with the labels that each got.

#1154 [forward port]: kata-deploy: Fix typo #591
  kata-deploy/README.md
Labels: forward-port

#1158 qemu: update qemu default config for arm
  qemu/default-configs/aarch64-softmmu.mak
  qemu/default-configs/arm-softmmu.mak
Labels: forward-port, needs-forward-port

#1164 snap: specify python version
  snap/snapcraft.yaml
Labels: no-backport-needed, no-forward-port-needed
